services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB!
    ports:
      - "27017:27017"
  update_infos:
    build:
      context: .
      dockerfile: update-infos.Dockerfile
    container_name: update-infos
    volumes:
      - .:/app
